import { describe, it, expect } from "vitest";
import { danishNumberToWords } from "./num2words-da.js";
import goldenCases from "./__fixtures__/num2words-da.json";

// The reference normalizes numbers with num2words(lang="da"); the port must
// reproduce it exactly or the LM sees different text. The golden fixture is the
// oracle (generated by conversion/gen_num2words_fixtures.py); these explicit
// cases document the behavior (and its quirks) for a human reader.

describe("danishNumberToWords — documented behavior", () => {
  it.each([
    ["1", "et"], // standalone 1 is "et", not "en"
    ["21", "enogtyve"], // …but the tens compound uses "en"
    ["60", "treds"], // num2words quirk: "treds", not the standard "tres"
    ["100", "ethundrede"], // hundreds are written without a space
    ["234", "tohundrede og fireogtredive"],
    ["1000", "ettusind"],
    ["1500", "ettusinde og femhundrede"],
    ["1000000", "en millioner"], // millions: "en" + always plural
    ["3,14", "tre komma et fire"], // decimals digit-by-digit, 1 -> "et"
    ["1.500", "et komma fem"], // a dot is a decimal point (1.5), not thousands
    ["-5", "minus fem"],
  ])("%s -> %s", (input, expected) => {
    expect(danishNumberToWords(input)).toBe(expected);
  });
});

describe("danishNumberToWords — parity with num2words(da) golden fixture", () => {
  it(`matches all ${goldenCases.length} golden cases`, () => {
    const mismatches = (goldenCases as [string, string][])
      .filter(([input, expected]) => danishNumberToWords(input) !== expected)
      .map(([input, expected]) => `${input}: got "${danishNumberToWords(input)}", want "${expected}"`);
    expect(mismatches).toEqual([]);
  });
});
